# Generated by Django 5.2.6 on 2025-12-10 13:39

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('type', models.TextField(blank=True, choices=[('patient', 'пациент'), ('doctor', 'доктор'), ('admin', 'администратор')], default='patient', null=True)),
                ('totp_key', models.CharField(blank=True, default=pyotp.random_hex, max_length=128, null=True)),
                ('can_see_statistics', models.BooleanField(blank=True, db_default=False, null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_patients', 'Может создавать пациентов'), ('can_see_statistics_page', 'Может видеть страницу статистики'), ('can_manage_doctors', 'Может управлять врачами'), ('can_manage_patients', 'Может управлять пациентами'), ('can_manage_appointments', 'Может управлять записями'), ('can_manage_medical_records', 'Может управлять медицинскими записями')],
            },
        ),
    ]
