# Generated by Django 5.2.6 on 2025-12-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='totp_key',
        ),
    ]
