# Generated by Django 5.2.6 on 2025-12-11 14:46

import pyotp
from django.db import migrations, models


def fill_totp_field(apps, schema_editor):
    UserProfile = apps.get_model("general", "UserProfile")
    for u in UserProfile.objects.all():
        u.totp_key = pyotp.random_base32()  
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_remove_userprofile_totp_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_key',
            field=models.CharField(blank=True, default=pyotp.random_base32, max_length=128, null=True),
        ),
        migrations.RunPython(fill_totp_field)
    ]