# Generated by Django 5.2.7 on 2026-02-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_userprofile_totp_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_create_researchers', 'Может создавать исследователей'), ('can_see_statistics_page', 'Может видеть страницу статистики'), ('can_manage_astronomers', 'Может управлять астрономами'), ('can_manage_researchers', 'Может управлять исследователями'), ('can_manage_observations', 'Может управлять наблюдениями'), ('can_manage_observation_records', 'Может управлять записями наблюдений')]},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.TextField(blank=True, choices=[('researcher', 'исследователь'), ('astronomer', 'астроном'), ('admin', 'администратор')], default='researcher', null=True),
        ),
    ]
