# Generated by Django 5.2.7 on 2026-02-08 06:38

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_userprofile_options_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='totp_key',
            field=models.CharField(blank=True, default=pyotp.random_base32, max_length=128, null=True),
        ),
    ]
