# Generated by Django 5.2.5 on 2025-11-01 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='ФИО')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('picture', models.ImageField(null=True, upload_to='spacecatalog_img', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Астроном',
                'verbose_name_plural': 'Астрономы',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название типа')),
                ('description', models.TextField(verbose_name='Описание типа')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('last_name', models.TextField(verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('card_number', models.CharField(verbose_name='Номер исследователя')),
                ('picture', models.ImageField(null=True, upload_to='spacecatalog_img', verbose_name='Фото')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Исследователь',
                'verbose_name_plural': 'Исследователи',
            },
        ),
        migrations.CreateModel(
            name='SpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('discovery_year', models.IntegerField(verbose_name='Год открытия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Расстояние (световые годы)')),
                ('mass', models.FloatField(blank=True, null=True, verbose_name='Масса (солнечные массы)')),
                ('astronomer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spacecatalog.astronomer', verbose_name='Открыватель')),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spacecatalog.objecttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Космический объект',
                'verbose_name_plural': 'Космические объекты',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='planned', max_length=20, verbose_name='Статус')),
                ('observation_date', models.DateField(blank=True, null=True, verbose_name='Дата наблюдения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacecatalog.researcher', verbose_name='Исследователь')),
                ('space_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacecatalog.spaceobject', verbose_name='Космический объект')),
            ],
            options={
                'verbose_name': 'Наблюдение',
                'verbose_name_plural': 'Наблюдения',
            },
        ),
    ]
