# Generated by Django 5.2.5 on 2025-12-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacecatalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='totp_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='TOTP ключ'),
        ),
    ]
