# Generated by Django 5.2.7 on 2026-02-06 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('phone', models.TextField(verbose_name='Телефон')),
                ('picture', models.ImageField(null=True, upload_to='observatories', verbose_name='Изображение')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Обсерватория',
                'verbose_name_plural': 'Обсерватории',
            },
        ),
        migrations.CreateModel(
            name='Astronomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('research_field', models.TextField(verbose_name='Область исследований')),
                ('picture', models.ImageField(null=True, upload_to='astronomers', verbose_name='Изображение')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='astronomer', to=settings.AUTH_USER_MODEL)),
                ('observatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observatory.observatory')),
            ],
            options={
                'verbose_name': 'Астроном',
                'verbose_name_plural': 'Астрономы',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Исследователь',
                'verbose_name_plural': 'Исследователи',
            },
        ),
        migrations.CreateModel(
            name='ObservationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(verbose_name='Заметки')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='Результаты')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('astronomer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observatory.astronomer')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observatory.researcher')),
            ],
            options={
                'verbose_name': 'Запись наблюдения',
                'verbose_name_plural': 'Записи наблюдений',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Статус')),
                ('astronomer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observatory.astronomer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='observatory.researcher')),
            ],
            options={
                'verbose_name': 'Наблюдение',
                'verbose_name_plural': 'Наблюдения',
            },
        ),
    ]
