# Generated by Django 5.2.7 on 2026-02-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0002_add_researcher_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='researchers', verbose_name='Изображение'),
        ),
    ]
