# Generated by Django 5.2.7 on 2026-02-08 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0004_remove_observationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('object_type', models.CharField(max_length=100, verbose_name='Тип объекта')),
                ('astronomer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='space_object', to='observatory.astronomer')),
            ],
            options={
                'verbose_name': 'Космический объект',
                'verbose_name_plural': 'Космические объекты',
            },
        ),
    ]
