# Generated by Django 5.2.7 on 2026-03-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0005_spaceobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronomer',
            name='research_field',
        ),
    ]
